project_id = "luorlnagxpsibarcygjm"

[functions.create-employee-account]
verify_jwt = false

[functions.submit-application]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.sign-contract]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
